/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Alley_stones.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Alley_stones.tsx 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ObjectSettingType } from '../../../../../../../types/GameType'
import { useBox } from '@react-three/cannon'

type GLTFResult = GLTF & {
  nodes: {
    Alley_stones_Light_Gray_0: THREE.Mesh
  }
  materials: {
    Light_Gray: THREE.MeshStandardMaterial
  }
}


export function Alley_stones(props: ObjectSettingType) {
  const { nodes, materials } = useGLTF('/models/object/Alley_stones.glb') as GLTFResult
  const [ref] = useBox<THREE.Mesh>(() => ({
        args: [1, 1, 1],
        mass: 0.1,
        position: props.position,
        rotation: props.rotation,
        linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한
        angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한
    }));
  return (
    <group position={[0, 0, 0]} dispose={null}>
      <mesh ref={ref} geometry={nodes.Alley_stones_Light_Gray_0.geometry} material={materials.Light_Gray} position={props.position} rotation={props.rotation} />
    </group>
  )
}

useGLTF.preload('/models/object/Alley_stones.glb')
