/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Barrel.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Barrel.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Barrel_1: THREE.Mesh;
    };
    materials: {
        ['Cartoon_Room_Mat.002']: THREE.MeshStandardMaterial;
    };
};

export function Barrel(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(
        '/models/object/Barrel.glb'
    ) as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Barrel_1.geometry}
                material={materials['Cartoon_Room_Mat.002']}
                position={[0, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.025}
            />
        </group>
    );
}

useGLTF.preload('/models/object/Barrel.glb');
