/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Dog_house.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Dog_house.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { ObjectSettingType } from '../../../../../../../types/GameType';
import { useBox } from '@react-three/cannon';
import React from 'react';

type GLTFResult = GLTF & {
    nodes: {
        Dog_house_Brown_2_0: THREE.Mesh;
        Dog_house_Gray_0: THREE.Mesh;
        Dog_house_Red_0: THREE.Mesh;
        Dog_house_Yellow_2_0: THREE.Mesh;
    };
    materials: {
        Brown_2: THREE.MeshStandardMaterial;
        Gray: THREE.MeshStandardMaterial;
        material: THREE.MeshStandardMaterial;
        Yellow_2: THREE.MeshStandardMaterial;
    };
};

function Dog_houseComponent(props: ObjectSettingType) {
    const { nodes, materials } = useGLTF(
        '/models/object/Dog_house.glb'
    ) as GLTFResult;
    const [ref] = useBox<THREE.Mesh>(() => ({
        args: [3, 3, 5],
        mass: 0.1,
        position: props.position,
        rotation: props.rotation,
        linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한
        angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한
    }));
    return (
        <group position={[0, 0, 0]} dispose={null}>
            <group>
                <mesh
                    ref={ref}
                    geometry={nodes.Dog_house_Brown_2_0.geometry}
                    material={materials.Brown_2}
                    position={props.position}
                    rotation={props.rotation}
                    scale={[2, 2, 2]}
                />
                <mesh
                    ref={ref}
                    geometry={nodes.Dog_house_Gray_0.geometry}
                    material={materials.Gray}
                    position={props.position}
                    rotation={props.rotation}
                    scale={[2, 2, 2]}
                />
                <mesh
                    ref={ref}
                    geometry={nodes.Dog_house_Red_0.geometry}
                    material={materials.material}
                    position={props.position}
                    rotation={props.rotation}
                    scale={[2, 2, 2]}
                />
                <mesh
                    ref={ref}
                    geometry={nodes.Dog_house_Yellow_2_0.geometry}
                    material={materials.Yellow_2}
                    position={props.position}
                    rotation={props.rotation}
                    scale={[2, 2, 2]}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/models/object/Dog_house.glb');

function areEqual(prevProps: ObjectSettingType, nextProps: ObjectSettingType) {
    return (
        prevProps.position[0] === nextProps.position[0] &&
        prevProps.position[1] === nextProps.position[1] &&
        prevProps.position[2] === nextProps.position[2]
    );
  }
  
export const Dog_house= React.memo(Dog_houseComponent, areEqual);