/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Floor_diamond.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Floor_diamond.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Floor_15: THREE.Mesh;
    };
    materials: {
        ['Cartoon_Room_Mat.002']: THREE.MeshStandardMaterial;
    };
    animations: any[];
};

export function Floor_diamond(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(
        '/models/object/Floor_diamond.glb'
    ) as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Floor_15.geometry}
                material={materials['Cartoon_Room_Mat.002']}
                position={[0, 0, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale-y={0.024}
                scale-x={0.0218}
                scale-z={0.01}
            />
        </group>
    );
}

useGLTF.preload('/models/object/Floor_diamond.glb');
