/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Flower_pot.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Flower_pot.tsx 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ObjectSettingType } from '../../../../../../../types/GameType'
import { useBox } from '@react-three/cannon'


type GLTFResult = GLTF & {
  nodes: {
    Flower_pot_Brown_2_0: THREE.Mesh
    Flower_pot_Forest_Green_0: THREE.Mesh
    Flower_pot_Red_0: THREE.Mesh
  }
  materials: {
    Brown_2: THREE.MeshStandardMaterial
    Forest_Green: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
}


export function Flower_pot(props: ObjectSettingType) {
  const { nodes, materials } = useGLTF('/models/object/Flower_pot.glb') as GLTFResult

  const [ref] = useBox<THREE.Mesh>(() => ({
        args: [1, 1, 1],
        mass: 0.1,
        position: props.position,
        rotation: props.rotation,
        linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한
        angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한
    }));
  return (
    <group position={[0, 0, 0]} dispose={null}>
      <group>
        <mesh ref={ref} geometry={nodes.Flower_pot_Brown_2_0.geometry} material={materials.Brown_2} position={props.position} rotation={props.rotation}/>
        <mesh ref={ref} geometry={nodes.Flower_pot_Forest_Green_0.geometry} material={materials.Forest_Green} position={props.position} rotation={props.rotation}/>
        <mesh ref={ref} geometry={nodes.Flower_pot_Red_0.geometry} material={materials.material} position={props.position} rotation={props.rotation}/>
      </group>
    </group>
  )
}

useGLTF.preload('/models/object/Flower_pot.glb')
