/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Light_pole_1.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Light_pole_1.tsx 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ObjectSettingType } from '../../../../../../../types/GameType'

import { useBox } from '@react-three/cannon'
type GLTFResult = GLTF & {
  nodes: {
    Light_pole_1_Gray_0: THREE.Mesh
    Light_pole_1_Light_Gray_0: THREE.Mesh
    Light_pole_1_Yellow_0: THREE.Mesh
  }
  materials: {
    Gray: THREE.MeshStandardMaterial
    Light_Gray: THREE.MeshStandardMaterial
    Yellow: THREE.MeshStandardMaterial
  }
}


export function Light_pole_1(props: ObjectSettingType) {
  const { nodes, materials } = useGLTF('/models/object/Light_pole_1.glb') as GLTFResult
  
  const [ref] = useBox<THREE.Mesh>(() => ({

    args: [1, 1, 1],

    mass: 0.1,

    position: props.position,

    rotation: props.rotation,

    linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한

    angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한

    }));
  return (
    <group position={[0, 0, 0]} dispose={null}>
      <group>
        <mesh ref={ref} geometry={nodes.Light_pole_1_Gray_0.geometry} material={materials.Gray} position={props.position} rotation={props.rotation}/>
        <mesh ref={ref} geometry={nodes.Light_pole_1_Light_Gray_0.geometry} material={materials.Light_Gray} position={props.position} rotation={props.rotation}/>
        <mesh ref={ref} geometry={nodes.Light_pole_1_Yellow_0.geometry} material={materials.Yellow} position={props.position} rotation={props.rotation}/>
      </group>
    </group>
  )
}

useGLTF.preload('/models/object/Light_pole_1.glb')
