/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Road_2.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Road_2.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

import { ObjectSettingType } from '../../../../../../../types/GameType';

import { useBox } from '@react-three/cannon';
import React from 'react';
type GLTFResult = GLTF & {
    nodes: {
        Road_2_Gray_0: THREE.Mesh;
        Road_2_Light_Gray_0: THREE.Mesh;
        Road_2_White_0: THREE.Mesh;
        Road_2_Yellow_0: THREE.Mesh;
    };
    materials: {
        Gray: THREE.MeshStandardMaterial;
        Light_Gray: THREE.MeshStandardMaterial;
        White: THREE.MeshStandardMaterial;
        Yellow: THREE.MeshStandardMaterial;
    };
};

function Road_2Component(props: ObjectSettingType) {
    const { nodes, materials } = useGLTF(
        '/models/object/Road_2.glb'
    ) as GLTFResult;

    const [ref] = useBox<THREE.Mesh>(() => ({
        args: [9, 9, 0.5],

        mass: 0.1,

        position: props.position,
        type: 'Static',
        rotation: props.rotation,

        linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한

        angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한
    }));
    return (
        <group position={[0, 0, 0]} dispose={null}>
            <group>
                <mesh
                    ref={ref}
                    geometry={nodes.Road_2_Gray_0.geometry}
                    material={materials.Gray}
                    position={props.position}
                    rotation={props.rotation}
                />
                <mesh
                    ref={ref}
                    geometry={nodes.Road_2_Light_Gray_0.geometry}
                    material={materials.Light_Gray}
                    position={props.position}
                    rotation={props.rotation}
                />
                <mesh
                    ref={ref}
                    geometry={nodes.Road_2_White_0.geometry}
                    material={materials.White}
                    position={props.position}
                    rotation={props.rotation}
                />
                <mesh
                    ref={ref}
                    geometry={nodes.Road_2_Yellow_0.geometry}
                    material={materials.Yellow}
                    position={props.position}
                    rotation={props.rotation}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/models/object/Road_2.glb');

function areEqual(prevProps: ObjectSettingType, nextProps: ObjectSettingType) {
    return (
        prevProps.position[0] === nextProps.position[0] &&
        prevProps.position[1] === nextProps.position[1] &&
        prevProps.position[2] === nextProps.position[2]
    );
}

export const Road_2 = React.memo(Road_2Component, areEqual);
