/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Table_1.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Table_1.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { ObjectSettingType } from '../../../../../../../types/GameType';

import { useBox } from '@react-three/cannon';
import React from 'react';
type GLTFResult = GLTF & {
    nodes: {
        Table_1_Brown_4_0: THREE.Mesh;
    };
    materials: {
        Brown_4: THREE.MeshStandardMaterial;
    };
};

function Table_1Component(props: ObjectSettingType) {
    const { nodes, materials } = useGLTF(
        '/models/object/Table_1.glb'
    ) as GLTFResult;

    const [ref] = useBox<THREE.Mesh>(() => ({
        args: [2, 1.5, 1.5],

        mass: 0.1,

        position: props.position,

        rotation: props.rotation,

        linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한

        angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한
    }));
    return (
        <group position={[0, 0, 0]} dispose={null}>
            <mesh
                ref={ref}
                geometry={nodes.Table_1_Brown_4_0.geometry}
                material={materials.Brown_4}
                position={props.position}
                rotation={props.rotation}
            />
        </group>
    );
}

useGLTF.preload('/models/object/Table_1.glb');

function areEqual(prevProps: ObjectSettingType, nextProps: ObjectSettingType) {
    return (
        prevProps.position[0] === nextProps.position[0] &&
        prevProps.position[1] === nextProps.position[1] &&
        prevProps.position[2] === nextProps.position[2]
    );
}

export const Table_1 = React.memo(Table_1Component, areEqual);
