/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Wall_white.glb -t -o src/components/content/canvas/maps/player/Wall_white.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { ObjectSettingType } from '../../../../../../../types/GameType';
import { useBox } from '@react-three/cannon';

type GLTFResult = GLTF & {
    nodes: {
        Wall_38: THREE.Mesh;
    };
    materials: {
        ['Cartoon_Room_Mat.002']: THREE.MeshStandardMaterial;
    };
};

export function Wall_white_Side(props: ObjectSettingType) {
    const { nodes, materials } = useGLTF(
        '/models/object/Wall_white.glb'
    ) as GLTFResult;
    const [ref] = useBox<THREE.Mesh>(() => ({
        args: [10, 1, 8],
        mass: 0.1,
        position: [props.position[0], props.position[1], props.position[2]],
        rotation: props.rotation,
        linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한
        angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한
    }));
    return (
        <group position={[-5, -4, 0]} dispose={null}>
            <mesh
                ref={ref}
                geometry={nodes.Wall_38.geometry}
                material={materials['Cartoon_Room_Mat.002']}
                position={[
                    props.position[0],
                    props.position[1],
                    props.position[2],
                ]}
                rotation={props.rotation}
                scale-y={0.01}
                scale-x={0.0202}
                scale-z={0.0202}
            />
        </group>
    );
}

useGLTF.preload('/models/object/Wall_white.glb');
