/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Wheelbarrow.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Wheelbarrow.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

import { ObjectSettingType } from '../../../../../../../types/GameType';

import { useBox } from '@react-three/cannon';
import React from 'react';
type GLTFResult = GLTF & {
    nodes: {
        Wheelbarrow_Brown_4_0: THREE.Mesh;
        Wheelbarrow_Brown__0: THREE.Mesh;
    };
    materials: {
        Brown_4: THREE.MeshStandardMaterial;
        Brown: THREE.MeshStandardMaterial;
    };
};

function WheelbarrowComponent(props: ObjectSettingType) {
    const { nodes, materials } = useGLTF(
        '/models/object/Wheelbarrow.glb'
    ) as GLTFResult;

    const [ref] = useBox<THREE.Mesh>(() => ({
        args: [2.8, 3.3, 3],

        mass: 0.1,

        position: props.position,

        rotation: props.rotation,

        linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한

        angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한
    }));
    return (
        <group position={[0, 0, -0.6]} dispose={null}>
            <group>
                <mesh
                    ref={ref}
                    geometry={nodes.Wheelbarrow_Brown_4_0.geometry}
                    material={materials.Brown_4}
                    position={props.position}
                    rotation={props.rotation}
                    scale={[2, 2, 2]}
                />
                <mesh
                    ref={ref}
                    geometry={nodes.Wheelbarrow_Brown__0.geometry}
                    material={materials.Brown}
                    position={props.position}
                    rotation={props.rotation}
                    scale={[2, 2, 2]}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/models/object/Wheelbarrow.glb');

function areEqual(prevProps: ObjectSettingType, nextProps: ObjectSettingType) {
    return (
        prevProps.position[0] === nextProps.position[0] &&
        prevProps.position[1] === nextProps.position[1] &&
        prevProps.position[2] === nextProps.position[2]
    );
}

export const Wheelbarrow = React.memo(WheelbarrowComponent, areEqual);
