/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/object/Wooden_box.glb -t -o src/components/content/canvas/maps/structures/ground/elements/Wooden_box.tsx 
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

import { ObjectSettingType } from '../../../../../../../types/GameType';

import { useBox } from '@react-three/cannon';
type GLTFResult = GLTF & {
    nodes: {
        Wooden_box_Brown_4_0: THREE.Mesh;
        Wooden_box_Gray_0: THREE.Mesh;
    };
    materials: {
        Brown_4: THREE.MeshStandardMaterial;
        Gray: THREE.MeshStandardMaterial;
    };
};

export function Wooden_box(props: ObjectSettingType) {
    const { nodes, materials } = useGLTF(
        '/models/object/Wooden_box.glb'
    ) as GLTFResult;

    const [ref] = useBox<THREE.Mesh>(() => ({
        args: [1, 1, 1],

        mass: 0.1,

        position: props.position,

        rotation: props.rotation,

        linearFactor: [0, 0, 0], // 모든 축에 대해 이동 제한

        angularFactor: [0, 0, 0], // 모든 축에 대해 회전 제한
    }));
    return (
        <group position={[0, 0, 0]} dispose={null}>
            <group>
                <mesh
                    ref={ref}
                    geometry={nodes.Wooden_box_Brown_4_0.geometry}
                    material={materials.Brown_4}
                    position={props.position}
                    rotation={props.rotation}
                />
                <mesh
                    ref={ref}
                    geometry={nodes.Wooden_box_Gray_0.geometry}
                    material={materials.Gray}
                    position={props.position}
                    rotation={props.rotation}
                />
            </group>
        </group>
    );
}

useGLTF.preload('/models/object/Wooden_box.glb');
